### ISSUE TITLE
Doesn't build with libheif 1.19+

### ISSUE THREAD

**Issue by felixonmars** [Cykooz/libheif-rs#28]
There appears to be some API changes: https://github.com/strukturag/libheif/commit/ecdeb8fe0e002a7c709d687782a3addf9a0b14d0#diff-3d7d4ade3135524be963ec0b461e86d0b1fbfef0c1083a1f2230811a92ac9a17R77

```
   Compiling libheif-rs v1.0.2
error[E0063]: missing fields `preload_range_hint`, `release_error_msg`, `release_file_range` and 1 other field in initializer of `heif_reader`
   --> /usr/src/debug/glycin/build/cargo-home/registry/src/index.crates.io-6f17d22bba15001f/libheif-rs-1.0.2/src/reader.rs:104:50
    |
104 | pub(crate) static HEIF_READER: lh::heif_reader = lh::heif_reader {
    |                                                  ^^^^^^^^^^^^^^^ missing `preload_range_hint`, `release_error_msg`, `release_file_range` and 1 other field

For more information about this error, try `rustc --explain E0063`.
error: could not compile `libheif-rs` (lib) due to 1 previous error```

**Comment by Cykooz** [comment]
At the moment I haven't finished a version of `libheif-rs` with support for `libheif 1.19`.
But I think you can use the current version of `libheif-rs` with `libheif 1.19` if you disable the default features of the crate in your `Cargo.toml`:
```toml
[dependencies]
libheif-rs = { version = "1.0.2", default-features = false }
```

When `libheif 1.19` becomes available in Microsoft's [vcpkg](https://github.com/microsoft/vcpkg/tree/master/ports/libheif), I will add support for it.

**Comment by felixonmars** [comment]
Thanks. I have verified that this fixes it on x86_64. But unfortunately I'm trying to build it on riscv64 :(

**Comment by Cykooz** [comment]
I have release `libheif-sys 2.2.0` with follow changes:
- `.h` files from `libheif` was embedded in the crate sources.
- Changed `build.rs` to use embedded `.h` files for the bindgen build stage
  instead of `.h` files from the installed `libheif` library.

  Now you can link the crate with any version of `libheif`
  that is backward compatible with the version supported by the crate.

So you can try to do a `cargo update` to use this version, and remove the changes I suggested earlier.
